---
application:
  name: "simple-web-chat"
  project: "By"
  organization: "QoveryCommunity"
  storage:
  - name: "H"
    size: "10"
    type: "fast_ssd"
    mount_point: "H"
routers:
- name: "main-simple-web-chat"
  routes:
  - application_name: "simple-web-chat"
    paths:
    - "/*"
